Update to 1.20.1 and add russian translation
hf02/scroll-for-worldedit pull request #15
Opened 2023-07-25 13:11 UTC by Rozbiynk

2023-07-26 01:01 UTC, hf02 requested changes
thx, just a single thing.

2023-07-26 06:42 UTC, Rozbiynk commented on src/main/resources/fabric.mod.json
> +	"version": "${version}",
what wrong?

2023-07-26 06:42 UTC, Rozbiynk commented on src/main/resources/fabric.mod.json
> +	"version": "${version}",
oh, I got it

2023-07-27 09:08 UTC, Rozbiynk commented
is now all good?

2023-07-28 11:05 UTC, Rozbiynk commented
oh

2023-07-29 02:16 UTC, merged

2023-07-29 02:17 UTC, hf02 commented
> is now all good?

yep, thanks!